"""
Knowledge Index - Searchable knowledge index (domain-agnostic)

Provides a unified searchable index over KnowledgeEntry objects.
Domain-specific knowledge is populated via registered builders.

Usage:
    # Default: uses registered or auto-discovered builder
    index = get_knowledge_index()
    results = index.search(query, max_results=3)

    # Explicit injection
    index = KnowledgeIndex(entries=[...])

    # Register a domain-specific builder
    register_knowledge_builder(my_builder_fn)
"""

import logging
from dataclasses import dataclass, field
from typing import List, Optional, Callable

logger = logging.getLogger(__name__)


@dataclass
class KnowledgeEntry:
    """Knowledge entry."""
    query_type: str  # "tool_tier", "api_behavior", "game_mechanic", "reasoning_example"
    name: str  # Knowledge-item name
    keywords: List[str]  # Keywords used for matching
    content: str  # Formatted knowledge text
    priority: int = 0  # Priority (used for sorting)


@dataclass
class KnowledgeQuery:
    """Knowledge retrieval query generated by the LLM."""
    query_type: str  # "tool_tier", "api_behavior", "ore_spawn", "mechanics"
    keywords: List[str]
    context: str = ""


# ── Builder registration ──

_knowledge_builder: Optional[Callable[[], List[KnowledgeEntry]]] = None


def register_knowledge_builder(builder: Callable[[], List[KnowledgeEntry]]):
    """Register a domain-specific knowledge builder.

    Invalidates the cached singleton so the next get_knowledge_index()
    call rebuilds with the new builder.
    """
    global _knowledge_builder, _knowledge_index
    _knowledge_builder = builder
    _knowledge_index = None


def _default_build_entries() -> List[KnowledgeEntry]:
    """Fallback when no builder registered. Returns empty list."""
    logger.warning(
        "[KnowledgeIndex] No knowledge builder registered — "
        "use register_knowledge_builder() or from_domain()"
    )
    return []


class KnowledgeIndex:
    """
    Searchable knowledge index (domain-agnostic).

    Receives pre-built entries via constructor or builds them from a
    registered domain-specific builder function.
    """

    def __init__(self, entries: Optional[List[KnowledgeEntry]] = None):
        if entries is not None:
            self.entries = list(entries)
        else:
            self.entries = []
            self._build_index()
        logger.info(f"[KnowledgeIndex] Index built with {len(self.entries)} entries")

    def _build_index(self):
        """Build index from registered or default builder.

        Kept as a method (rather than inlined in __init__) so existing
        test monkey-patching patterns continue to work.
        """
        if _knowledge_builder is not None:
            self.entries = _knowledge_builder()
        else:
            self.entries = _default_build_entries()

    def search(self, query: KnowledgeQuery, max_results: int = 3) -> List[str]:
        """
        Search for knowledge entries matching the query.

        Args:
            query: Knowledge query
            max_results: Maximum number of results to return

        Returns:
            List of matched knowledge texts
        """
        matching = []

        for entry in self.entries:
            score = self._calculate_match_score(entry, query)
            if score > 0:
                matching.append((score, entry))

        # Sort by score
        matching.sort(key=lambda x: (-x[0], -x[1].priority))

        # Return the top N results
        return [entry.content for _, entry in matching[:max_results]]

    def _calculate_match_score(self, entry: KnowledgeEntry, query: KnowledgeQuery) -> float:
        """Compute the match score."""
        score = 0.0

        # Bonus for query-type match
        if entry.query_type == query.query_type:
            score += 5.0

        # Keyword matching
        entry_keywords_lower = [k.lower() for k in entry.keywords]
        matched_via_keywords = set()
        for kw in query.keywords:
            kw_lower = kw.lower()
            # Exact match
            if kw_lower in entry_keywords_lower:
                score += 3.0
                matched_via_keywords.add(kw_lower)
            # Partial match
            elif any(kw_lower in ek for ek in entry_keywords_lower):
                score += 1.5
                matched_via_keywords.add(kw_lower)
            elif any(ek in kw_lower for ek in entry_keywords_lower):
                score += 1.0
                matched_via_keywords.add(kw_lower)

        # Content-text matching: query keywords appearing in the fact/implications text.
        # Weight lower than keyword matching (+1.0 vs +3.0), keeping keyword priority.
        # Only applies to words not already matched by keywords (avoid double counting).
        # Minimum length 3, to filter out noise words like "a", "to", "in".
        content_lower = entry.content.lower()
        for kw in query.keywords:
            kw_lower = kw.lower()
            if kw_lower not in matched_via_keywords and len(kw_lower) >= 3 and kw_lower in content_lower:
                score += 1.0

        # Context matching (if available)
        if query.context:
            context_lower = query.context.lower()
            for kw in entry.keywords:
                if kw.lower() in context_lower:
                    score += 0.5

        return score



# Module-level singleton
_knowledge_index: Optional[KnowledgeIndex] = None


def get_knowledge_index() -> KnowledgeIndex:
    """Get the knowledge-index singleton."""
    global _knowledge_index
    if _knowledge_index is None:
        _knowledge_index = KnowledgeIndex()
    return _knowledge_index
