"""
SkillNode dataclass

A node in the Skill Graph, representing one skill.

Aligned with the paper "Evolving Programmatic Skill Networks":

    s = (C_s, P_s, E_s, Children(s))

where:
    C_s = code         control flow (JavaScript code)
    P_s = parameters   parameter set
    E_s = (preconditions, expected_effects)  preconditions / postconditions
    Children(s) = children  list of child skills

Value Function（Section 2.2）：
    V(s) = p̂_s - u_s

where p̂_s is the Laplace-smoothed success rate and u_s is the uncertainty.
"""

import copy
import math
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Any, Optional, Tuple, TYPE_CHECKING

if TYPE_CHECKING:
    from .coverage import CoverageType

from .precondition import SkillPrecondition, SkillEffect, ActualEffect
from .execution import SkillExecutionTrace, SkillStatistics
from .gradients import SkillGradients, SkillGradientItem
from .version import SkillVersion


# ═══════════════════════════════════════════════════════════════════════════════
# Unified code update interface - type definitions
# ═══════════════════════════════════════════════════════════════════════════════


class CodeSource(Enum):
    """
    Source of a code update.

    Identifies the source of a code change; different sources have different trust levels and handling logic:
    - LLM: LLM-generated code; requires execution validation (for stable skills)
    - REFACTOR: code generated by the refactor system; trusted update
    - OPTIMIZER: code repaired by the optimizer; trusted update
    - MANUAL: manually edited code; trusted update
    """
    LLM = "llm"
    REFACTOR = "refactor"
    OPTIMIZER = "optimizer"
    MANUAL = "manual"


@dataclass
class UpdateResult:
    """
    Result of a code update.

    Attributes:
        success: whether the update succeeded (i.e. whether code was written to node.code)
        reason: result reason code for programmatic dispatch
            - "code_unchanged": code identical; no update needed
            - "wrapper_redirect": wrapper protection; redirect to covered_by
            - "wrapper_architecture_violation": wrapper architecture violation (LLM attempted to override)
            - "wrapper_protected": wrapper is protected; force=True required
            - "stable_needs_verification": stable skill needs execution validation
            - "updated": update succeeded
        need_verification: whether execution validation is required to confirm the update
        allow_execution: whether execution is allowed (even when the update is rejected, execution validation may be permitted)
        redirect_to: for wrapper_redirect, the name of the skill that should be modified instead
        message: human-readable message for logs or hints
    """
    success: bool
    reason: str = ""
    need_verification: bool = False
    allow_execution: bool = True
    redirect_to: Optional[str] = None
    message: str = ""


@dataclass
class ConfirmResult:
    """
    Confirmation result after execution validation.

    Attributes:
        adopted: whether the pending code was adopted (written to node.code)
        message: human-readable message
    """
    adopted: bool
    message: str = ""


class SkillNode:
    """
    A node in the Skill Graph, representing one skill.

    Paper formula: s = (C_s, P_s, E_s, Children(s))

    Attributes:
        name: skill name (unique identifier)
        code: C_s - control flow, JavaScript async function
        parameters: P_s - parameter set
        preconditions: E_s^pre - preconditions
        expected_effects: E_s^post - expected effects
        children: Children(s) - list of child skills

    Paper-aligned aliases (via skill_network module):
        Skill = SkillNode
        Precondition = SkillPrecondition
        Effect = SkillEffect
    """

    def __init__(
        self,
        name: str,
        code: str = "",
        description: str = "",
        version: str = "1.0.0",
    ):
        self.name = name

        # Core identity
        self.code = code
        self.description = description

        # Extended attributes
        self.preconditions: List[SkillPrecondition] = []  # preconditions
        self.expected_effects: List[SkillEffect] = []  # expected effects
        self.actual_effects: List[ActualEffect] = []  # actual effects (state changes from each execution)
        self.versions: List[SkillVersion] = []  # version history
        self.statistics = SkillStatistics()  # statistics
        self.gradients = SkillGradients()  # gradient information

        # Graph structural info
        self.parents: List[str] = []  # list of parent skills that call this skill
        self.children: List[str] = []  # list of child skills called by this skill (in call order)
        self.in_degree: int = 0  # in-degree (number of skills calling this one)
        self.out_degree: int = 0  # out-degree (number of skills this one calls)

        # Optimization control
        self.stop_gradient: bool = False  # whether to stop gradient propagation (no optimization needed)

        # Parameterization support
        self.parameters: Dict[str, Dict[str, Any]] = {}  # parameter metadata
        # Format: {
        # "paramName": {
        # "type": "number|string|boolean|array",
        # "default": default_value,
        # "description": "parameter description",
        # "semantic": {  # full parameter semantics (v5.1+)
        # "quantity_semantic": "target_total|delta|none",
        # # - target_total: target total to be reached
        # # - delta: incremental quantity
        # # - none: non-quantity parameter
        # "direction": "input|output|config|bidirectional",
        # # - input: input material type (e.g. logType -> oak_log)
        # # - output: output product type (e.g. plankType -> oak_planks)
        # # - config: configuration parameter
        # # - bidirectional: context-dependent
        # "transform_hint": {...} | null,  # input-material mapping rules
        # "config_context": "fuel|log|tool|block" | null,
        # "is_fuel_param": bool,
        # "inferred_by": "parameter_extractor|llm|rule",
        # "confidence": 0.0-1.0
        # }
        # # Backward compatible: legacy format "semantic": "target_total|delta|config" still supported
        # }
        # }

        # Refactor/coverage-related fields
        self.is_covered: bool = False  # whether this skill is covered by another
        self.covered_by: Optional[str] = None  # which skill covers this one (the general skill's name)
        self.coverage_type: Optional['CoverageType'] = None  # coverage type enum
        self.is_general_skill: bool = False  # whether this is a general skill (used for sibling specialization cases)

        # Part 18: runtime-rollback fields
        self.refactor_failures: List[Dict[str, Any]] = []  # records failures after a refactor
        self.original_code_before_refactor: Optional[str] = None  # code before refactor (for rollback)

        # Deprecation: set when the Graph Planner produces a task-specific
        # composition with low reuse value (the node stays in the graph as
        # an audit trail; planner/effect-matcher/precondition-checker skip it).
        self.is_deprecated: bool = False
        self.deprecation_reason: Optional[str] = None
        self.deprecated_for_task: Optional[str] = None  # task it was deprecated for

        # Experimental skill fields (new skills that have failed but are not yet validated)
        self.is_experimental: bool = False  # whether this is an experimental skill (failed on first execution)
        self.first_failure_reason: Optional[str] = None  # first-failure reason
        self.experimental_retry_count: int = 0  # retry count for the experimental skill
        self.max_experimental_retries: int = 4  # maximum retries (aligned with action_agent_task_max_retries)
        self.experimental_task: Optional[str] = None  # task associated with the experimental skill

        # Experimental Skill lifecycle management fields (newly added)
        self.created_for_task: Optional[str] = None  # which task this skill was first created for
        self.is_verified: bool = False  # whether validated by a task (has completed a task successfully)

        # Task-specific skill marker (in-memory only; not persisted to code/ or vectordb)
        self.is_task_specific: bool = False

        # Gradual-deprecation fields (improved version)
        self.consecutive_failures: int = 0  # consecutive-failure count
        self.task_failures: Dict[str, int] = {}  # failure counts per task {task: count}
        self.deprecation_threshold: int = 3  # consecutive failures before deprecation (default 3)
        self.task_failure_threshold: int = 2  # failures on the same task before per-task deprecation (default 2)

        # Semantic confidence: grows with the number of execution samples; represents trust in preconditions and effects
        self.semantics_confidence: float = 0.0  # 0.0-1.0, computed from the number of execution samples

        # Value-function parameters (for planning and skill-update control)
        self.value_function_lambda: float = 1.0  # λ parameter, default 1.0
        self.value_function_alpha: float = 1.0  # α parameter, default 1.0
        self.value_function_beta: float = 1.0  # β parameter, default 1.0

        # Initialize version history
        if code or description:
            self.versions.append(SkillVersion(
                version=version,
                code=code,
                description=description,
                change_log="Initial version"
            ))

    @property
    def value_function(self) -> float:
        """
        Value function: V(s) = p_s - λ * u_s

        Where:
        - p_s is the Bayesian-smoothed success rate: p_s = (n_succ + α) / (n_succ + n_fail + α + β)
        - u_s is uncertainty: u_s = (n_s + 1)^(-1/2)
        - n_succ, n_fail, n_s are the success, failure, and total usage counts respectively

        Returns:
            float: the skill's value function value
        """
        n_succ = self.statistics.successful_executions
        n_fail = self.statistics.failed_executions
        n_s = self.statistics.total_executions

        # Bayesian-smoothed success rate
        alpha = self.value_function_alpha
        beta = self.value_function_beta
        p_s = (n_succ + alpha) / (n_succ + n_fail + alpha + beta) if (n_succ + n_fail + alpha + beta) > 0 else 0.0

        # Uncertainty
        u_s = math.pow(n_s + 1, -0.5)

        # Value function
        lambda_val = self.value_function_lambda
        v_s = p_s - lambda_val * u_s

        return v_s

    def add_precondition(self, precondition: SkillPrecondition):
        """Add a precondition."""
        self.preconditions.append(precondition)

    def add_effect(self, effect: SkillEffect):
        """Add an expected effect."""
        self.expected_effects.append(effect)

    def add_version(self, version: SkillVersion):
        """Add a new version."""
        self.versions.append(version)
        # Contract gate: only promote contract-valid versions to be "active" / retrievable.
        if getattr(version, "is_contract_valid", True):
            # Update current code and description to the latest version
            self.code = version.code
            self.description = version.description
        else:
            reason = ""
            try:
                if getattr(version, "contract_violations", None):
                    reason = f" violations={version.contract_violations[:2]}"
            except Exception:
                reason = ""
            print(f"\033[33m[Contract Gate] Version {version.version} for skill '{self.name}' is contract-invalid; not promoting to active code.{reason}\033[0m")

    def get_latest_version(self) -> Optional[SkillVersion]:
        """Get the latest version."""
        if self.versions:
            return self.versions[-1]
        return None

    def get_version(self, version: str) -> Optional[SkillVersion]:
        """Get a version by its version number."""
        for v in self.versions:
            if v.version == version:
                return v
        return None

    def add_execution_to_window(self, execution_id: str, success: bool, version: str = None):
        """
        Append an execution record to the current version's sliding window.

        Args:
            execution_id: execution ID
            success: whether the execution succeeded
            version: version number (uses the latest version when None)
        """
        if version is None:
            latest_version = self.get_latest_version()
            if latest_version:
                version = latest_version.version
            else:
                return

        version_obj = self.get_version(version)
        if not version_obj:
            return

        # Append execution record to the window
        version_obj.execution_window.append({
            "execution_id": execution_id,
            "success": success,
            "timestamp": datetime.now().isoformat(),
            "version": version,
        })

        # Keep the window size bounded
        window_size = version_obj.sliding_window_size
        if len(version_obj.execution_window) > window_size:
            version_obj.execution_window = version_obj.execution_window[-window_size:]

    def get_version_success_rate(self, version: str = None, use_window: bool = True) -> float:
        """
        Get the success rate for a specified version.

        Args:
            version: version number (uses the latest version when None)
            use_window: whether to use the sliding window (True) or all-time statistics (False)

        Returns:
            float: success rate
        """
        if version is None:
            latest_version = self.get_latest_version()
            if latest_version:
                version = latest_version.version
            else:
                return 0.0

        version_obj = self.get_version(version)
        if not version_obj:
            return 0.0

        if use_window and version_obj.execution_window:
            # Use the sliding window
            window = version_obj.execution_window
            if len(window) == 0:
                return 0.0
            successful = sum(1 for e in window if e.get("success", False))
            return successful / len(window)
        else:
            # Use all-time statistics (from statistics_snapshot)
            snapshot = version_obj.statistics_snapshot
            total = snapshot.get("total_executions", 0)
            if total == 0:
                return 0.0
            successful = snapshot.get("successful_executions", 0)
            return successful / total

    def check_performance_degradation(
        self,
        current_version: str = None,
        degradation_threshold: float = 0.15,
        min_window_size: int = 5,
    ) -> Tuple[bool, Optional[str], float, float]:
        """
        Check whether the current version has regressed relative to the previous one.

        Args:
            current_version: current version number (uses the latest version when None)
            degradation_threshold: regression threshold (default 0.15, i.e. 15%)
            min_window_size: minimum window size; need at least this many executions to detect

        Returns:
            Tuple[bool, Optional[str], float, float]:
                (degraded?, previous version, current-version success_rate, previous-version success_rate)
        """
        if current_version is None:
            latest_version = self.get_latest_version()
            if not latest_version:
                return False, None, 0.0, 0.0
            current_version = latest_version.version

        current_version_obj = self.get_version(current_version)
        if not current_version_obj:
            return False, None, 0.0, 0.0

        # Check window size
        if len(current_version_obj.execution_window) < min_window_size:
            return False, None, 0.0, 0.0

        # Get the previous version
        previous_version = current_version_obj.affected_subgraph.get("previous_version")
        if not previous_version:
            # If no record, try to find one in version history
            current_idx = None
            for i, v in enumerate(self.versions):
                if v.version == current_version:
                    current_idx = i
                    break
            if current_idx is not None and current_idx > 0:
                previous_version = self.versions[current_idx - 1].version
            else:
                return False, None, 0.0, 0.0

        previous_version_obj = self.get_version(previous_version)
        if not previous_version_obj:
            return False, None, 0.0, 0.0

        # Compute success rates for both versions
        current_sr = self.get_version_success_rate(current_version, use_window=True)
        previous_sr = self.get_version_success_rate(previous_version, use_window=False)

        # Check whether it has regressed
        degradation = previous_sr - current_sr
        is_degraded = degradation >= degradation_threshold

        return is_degraded, previous_version, current_sr, previous_sr

    def rollback_to_version(self, target_version: str) -> bool:
        """
        Roll back to a specified version.

        Args:
            target_version: target version number (e.g. "1.0.0")

        Returns:
            bool: whether the rollback succeeded
        """
        target_ver = self.get_version(target_version)
        if not target_ver:
            print(f"\033[31m[Rollback] Error: version '{target_version}' not found\033[0m")
            return False

        # Create a rollback version (based on the target version)
        current_version = self.get_latest_version()
        if current_version and current_version.version == target_version:
            print(f"\033[33m[Rollback] Already on version '{target_version}'; nothing to roll back\033[0m")
            return False

        # Determine the new version number (rollback version)
        if current_version:
            version_parts = current_version.version.split(".")
            version_parts[-1] = str(int(version_parts[-1]) + 1)
            rollback_version = ".".join(version_parts)
        else:
            rollback_version = target_version

        # Restore all attributes from the target version
        self.code = target_ver.code
        self.description = target_ver.description

        # Restore preconditions
        if target_ver.preconditions:
            self.preconditions = [copy.deepcopy(p) for p in target_ver.preconditions]

        # Restore effects
        if target_ver.effects:
            self.expected_effects = [copy.deepcopy(e) for e in target_ver.effects]

        # Restore parameters
        if target_ver.parameters:
            self.parameters = copy.deepcopy(target_ver.parameters)

        # Restore value-function parameters (if present in snapshot)
        if "value_function_lambda" in target_ver.statistics_snapshot:
            self.value_function_lambda = target_ver.statistics_snapshot.get("value_function_lambda", 1.0)
            self.value_function_alpha = target_ver.statistics_snapshot.get("value_function_alpha", 1.0)
            self.value_function_beta = target_ver.statistics_snapshot.get("value_function_beta", 1.0)

        # Create a rollback version record
        rollback_version_obj = SkillVersion(
            version=rollback_version,
            code=target_ver.code,
            description=target_ver.description,
            change_log=f"Rollback to version {target_version}",
            preconditions=[copy.deepcopy(p) for p in target_ver.preconditions] if target_ver.preconditions else [],
            effects=[copy.deepcopy(e) for e in target_ver.effects] if target_ver.effects else [],
            parameters=copy.deepcopy(target_ver.parameters) if target_ver.parameters else {},
            value_function=target_ver.value_function,
            statistics_snapshot=copy.deepcopy(target_ver.statistics_snapshot) if target_ver.statistics_snapshot else {},
            update_source="rollback",
            update_reason=f"Rollback from {current_version.version if current_version else 'unknown'} to {target_version}",
        )
        self.versions.append(rollback_version_obj)

        print(f"\033[32m[Rollback] Successfully rolled back to version '{target_version}'; created rollback version '{rollback_version}'\033[0m")
        return True

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict (for serialization)."""
        return {
            "name": self.name,
            "code": self.code,
            "description": self.description,
            "preconditions": [
                {
                    "description": p.description,
                    "code": p.code,
                    "state_representation": p.state_representation,
                    "condition": p.condition,
                    "source_skill": p.source_skill
                }
                for p in self.preconditions
            ],
            "expected_effects": [
                {
                    "description": s.description,
                    "code": s.code,
                    "state_representation": s.state_representation,
                    "is_primary": getattr(s, 'is_primary', False),
                    "condition": s.condition,
                    "source_skill": s.source_skill
                }
                for s in self.expected_effects
            ],
            "actual_effects": [
                {
                    "execution_id": s.execution_id,
                    "timestamp": s.timestamp,
                    "description": s.description,
                    "inventory_changes": s.inventory_changes,
                    "position_changes": s.position_changes,
                    "equipment_changes": s.equipment_changes,
                    "block_changes": s.block_changes,
                    "verified": s.verified,
                }
                for s in self.actual_effects[-50:]  # only keep the most recent 50 actual effects
            ],
            "versions": [
                {
                    "version": v.version,
                    "created_at": v.created_at,
                    "change_log": v.change_log,
                    "code": v.code,
                    "description": v.description,
                    "preconditions": [
                        {
                            "description": p.description,
                            "code": p.code,
                            "state_representation": p.state_representation,
                            "condition": p.condition,
                            "source_skill": p.source_skill
                        }
                        for p in v.preconditions
                    ],
                    "effects": [
                        {
                            "description": e.description,
                            "code": e.code,
                            "state_representation": e.state_representation,
                            "is_primary": getattr(e, 'is_primary', False),
                            "condition": e.condition,
                            "source_skill": e.source_skill
                        }
                        for e in v.effects
                    ],
                    "parameters": v.parameters,
                    "value_function": v.value_function,
                    "statistics_snapshot": v.statistics_snapshot,
                    "update_source": v.update_source,
                    "update_reason": v.update_reason,
                    "optimization_id": v.optimization_id,
                    "used_feedbacks": v.used_feedbacks,
                    "backpropagation_info": v.backpropagation_info,
                    "affected_subgraph": v.affected_subgraph,
                    "sliding_window_size": v.sliding_window_size,
                    "execution_window": v.execution_window,
                }
                for v in self.versions
            ],
            "statistics": {
                "total_executions": self.statistics.total_executions,
                "successful_executions": self.statistics.successful_executions,
                "failed_executions": self.statistics.failed_executions,
                "success_rate": self.statistics.success_rate,
                "execution_traces": [
                    asdict(trace) for trace in self.statistics.execution_traces[-10:]  # only keep the most recent 10
                ]
            },
            "graph_info": {
                "parents": self.parents,
                "children": self.children,
                "in_degree": self.in_degree,
                "out_degree": self.out_degree,
            },
            "stop_gradient": self.stop_gradient,
            "gradients": {
                "reflections": [asdict(item) for item in self.gradients.reflections],
                "feedback": [asdict(item) for item in self.gradients.feedback],
                "optimization_suggestions": [asdict(item) for item in self.gradients.optimization_suggestions],
            },
            "parameters": self.parameters,  # parameter metadata
            "refactor_info": {
                "is_covered": self.is_covered,
                "covered_by": self.covered_by,
                "coverage_type": self.coverage_type.value if self.coverage_type else None,
                "is_general_skill": self.is_general_skill,
            },
            "is_task_specific": getattr(self, 'is_task_specific', False),  # task-specific marker
            "deprecation_info": {
                "is_deprecated": self.is_deprecated,
                "deprecation_reason": self.deprecation_reason,
                "deprecated_for_task": self.deprecated_for_task,
                # Gradual-deprecation fields
                "consecutive_failures": self.consecutive_failures,
                "task_failures": self.task_failures,
                "deprecation_threshold": self.deprecation_threshold,
                "task_failure_threshold": self.task_failure_threshold,
                # experimental-related fields
                "is_experimental": getattr(self, 'is_experimental', False),
                "first_failure_reason": getattr(self, 'first_failure_reason', None),
                "experimental_retry_count": getattr(self, 'experimental_retry_count', 0),
                "max_experimental_retries": getattr(self, 'max_experimental_retries', 4),
                "experimental_task": getattr(self, 'experimental_task', None),
                # Experimental Skill lifecycle management fields (newly added)
                "created_for_task": getattr(self, 'created_for_task', None),
                "is_verified": getattr(self, 'is_verified', False),
            },
            "semantics_confidence": getattr(self, 'semantics_confidence', 0.0),
            "value_function": self.value_function,  # value-function value
            "value_function_params": {
                "lambda": self.value_function_lambda,
                "alpha": self.value_function_alpha,
                "beta": self.value_function_beta,
            }
        }

    def mark_execution_failed(self, task: str = None, error: str = None) -> Dict[str, Any]:
        """
        Mark one failed execution: only increment counters and return whether deletion is warranted.

        Phase 9 refactor: do not set is_deprecated directly; let on_task_completed() handle removal centrally.

        Args:
            task: associated task (optional)
            error: error message (optional)

        Returns:
            Dict[str, Any]: contains state info and a should_deprecate flag
            - should_deprecate: whether the deletion threshold is reached (caller decides whether to delete)
            - deprecation_reason: deletion reason (when should_deprecate=True)
        """
        result = {
            "was_deprecated": self.is_deprecated,
            "now_deprecated": self.is_deprecated,  # Phase 9: no longer mutated here
            "consecutive_failures": 0,
            "task_failures": 0,
            "should_deprecate": False,  # Phase 9: new; caller decides whether to delete
            "deprecation_reason": None,
            "experimental_retry_count": 0,
            "experimental_exceeded_retries": False,
            # Legacy field compatibility
            "deprecation_triggered": False,
            "reason": None,
        }

        # Increment the consecutive-failure count
        self.consecutive_failures += 1
        result["consecutive_failures"] = self.consecutive_failures

        # Record the first-failure reason
        if self.consecutive_failures == 1 and error:
            self.first_failure_reason = error

        # If associated with a task, increment the per-task failure count
        if task:
            self.task_failures[task] = self.task_failures.get(task, 0) + 1
            result["task_failures"] = self.task_failures[task]

        # ========== Experimental Skill lifecycle management ==========
        if self.is_experimental:
            # Check whether this is a retry of the same task
            if self.experimental_task and task and self.experimental_task != task:
                # Different task; do not increment (experimental state continues)
                pass
            else:
                self.experimental_retry_count += 1
                if not self.experimental_task:
                    self.experimental_task = task

            result["experimental_retry_count"] = self.experimental_retry_count

            # Check whether max retries was exceeded
            if self.experimental_retry_count >= self.max_experimental_retries:
                # Phase 9: do not set is_deprecated directly; only return the flag
                deprecation_reason = (
                    f"Experimental skill exceeded max retries ({self.experimental_retry_count}/{self.max_experimental_retries})"
                )
                if self.first_failure_reason:
                    deprecation_reason += f". First failure reason: {self.first_failure_reason[:100]}"

                result["experimental_exceeded_retries"] = True
                result["should_deprecate"] = True
                result["deprecation_reason"] = deprecation_reason
                # Legacy field compatibility
                result["deprecation_triggered"] = True
                result["reason"] = deprecation_reason

                print(f"\033[33m[Experimental Skill] Reached deletion threshold ({self.experimental_retry_count}/{self.max_experimental_retries}); awaiting on_task_completed for removal\033[0m")
                return result

        # ========== Normal deprecation logic ==========
        should_deprecate = False
        deprecation_reason = None

        # Strategy 1: consecutive failures exceed the threshold
        if self.consecutive_failures >= self.deprecation_threshold:
            should_deprecate = True
            deprecation_reason = f"Consecutive failures: {self.consecutive_failures} (threshold: {self.deprecation_threshold})"
            if error:
                deprecation_reason += f"; last error: {error[:100]}"

        # Strategy 2: same-task failures exceed the threshold
        if task and self.task_failures.get(task, 0) >= self.task_failure_threshold:
            should_deprecate = True
            task_fail_count = self.task_failures[task]
            if deprecation_reason:
                deprecation_reason += f"; task '{task}' failed {task_fail_count} times"
            else:
                deprecation_reason = f"Task '{task}' failed {task_fail_count} times (threshold: {self.task_failure_threshold})"

        # Phase 9: do not set is_deprecated directly; only return the flag
        if should_deprecate:
            result["should_deprecate"] = True
            result["deprecation_reason"] = deprecation_reason
            # Legacy field compatibility
            result["deprecation_triggered"] = True
            result["reason"] = deprecation_reason

        return result

    def mark_execution_success(self, task: str = None) -> Dict[str, Any]:
        """
        Mark one successful execution; may restore a deprecated skill.

        Args:
            task: associated task (optional)

        Returns:
            Dict[str, Any]: information about deprecation-state changes
            - should_trigger_refactor: [Fix 7] if an experimental skill succeeds for the first time, trigger the delayed refactor
        """
        result = {
            "was_deprecated": self.is_deprecated,
            "now_deprecated": False,
            "reactivated": False,
            "consecutive_failures_reset": self.consecutive_failures > 0,
            "was_experimental": self.is_experimental,
            "now_experimental": False,
            "experimental_verified": False,
            "should_trigger_refactor": False,  # [Fix 7] delayed-refactor trigger flag
        }

        # Reset consecutive-failure count
        self.consecutive_failures = 0

        # If associated with a task, decrement the per-task failure count (but not below 0)
        if task and task in self.task_failures:
            self.task_failures[task] = max(0, self.task_failures[task] - 1)
            # If the task's failure count drops to 0, remove it from the dict
            if self.task_failures[task] == 0:
                del self.task_failures[task]

        # If previously deprecated and now succeeded, consider restoration
        if self.is_deprecated:
            # Restoration condition: consecutive successful executions (success resets consecutive failures)
            self.is_deprecated = False
            self.deprecation_reason = None
            self.deprecated_for_task = None
            result["reactivated"] = True

        # If it was experimental and now succeeded, clear the flag and trigger the delayed refactor
        if self.is_experimental:
            self.is_experimental = False
            self.is_verified = True  # mark as validated
            self.first_failure_reason = None
            self.experimental_retry_count = 0
            self.experimental_task = None
            result["experimental_verified"] = True
            result["should_trigger_refactor"] = True  # [Fix 7] inform the caller to trigger the delayed refactor
            print(f"\033[32m[Experimental Skill] Successfully validated! is_verified=True; delayed refactor will be triggered\033[0m")

        result["now_deprecated"] = self.is_deprecated
        result["now_experimental"] = self.is_experimental
        return result



    # ═══════════════════════════════════════════════════════════════════════════
    # Unified code-update interface
    # ═══════════════════════════════════════════════════════════════════════════

    def update_code(
        self,
        new_code: str,
        source: CodeSource,
        force: bool = False
    ) -> UpdateResult:
        """
        Unified entry point for code updates.

        All code modifications should go through this method to ensure:
        1. node.code is the single source of truth for the code
        2. The Wrapper architecture is protected
        3. Stable-skill updates require execution validation

        Rules (in priority order):
        1. Identical code → skip
        2. Wrapper architecture protection → block/redirect
        3. System source (REFACTOR/OPTIMIZER) → trusted update
        4. Experimental skill → free update
        5. Stable skill + LLM → deferred validation (adoption requires successful execution)

        Args:
            new_code: new code
            source: code source (CodeSource enum)
            force: whether to force an update (bypass wrapper protection)

        Returns:
            UpdateResult: the update result
        """
        # ═══════════════════════════════════════════════════════════════════
        # Rule 1: whether the code is identical
        # ═══════════════════════════════════════════════════════════════════
        if new_code.strip() == self.code.strip():
            return UpdateResult(success=True, reason="code_unchanged")

        # ═══════════════════════════════════════════════════════════════════
        # Rule 2: Wrapper architecture protection
        # ═══════════════════════════════════════════════════════════════════
        if self._should_protect_wrapper(new_code):
            covered_by = getattr(self, 'covered_by', 'unknown')

            if source == CodeSource.OPTIMIZER:
                # Redirect the optimization request to general_skill
                return UpdateResult(
                    success=False,
                    reason="wrapper_redirect",
                    redirect_to=covered_by,
                    message=f"This is a wrapper. Optimize {covered_by} instead."
                )
            elif source == CodeSource.LLM:
                # Allow execution validation but flag as rejected (will not be adopted)
                self._pending_code = new_code
                self._pending_source = source
                self._pending_rejected = True
                return UpdateResult(
                    success=False,
                    reason="wrapper_architecture_violation",
                    allow_execution=True,
                    message=f"Wrapper to {covered_by}. Full implementation may break architecture."
                )
            elif not force:
                return UpdateResult(
                    success=False,
                    reason="wrapper_protected",
                    message=f"Use force=True or modify {covered_by}"
                )

        # ═══════════════════════════════════════════════════════════════════
        # Rule 3: trusted system source (REFACTOR, OPTIMIZER) update
        # ═══════════════════════════════════════════════════════════════════
        if source in [CodeSource.REFACTOR, CodeSource.OPTIMIZER]:
            self._clear_pending()
            return self._do_update(new_code, source)

        # ═══════════════════════════════════════════════════════════════════
        # Rule 4: experimental skill may be freely updated
        # ═══════════════════════════════════════════════════════════════════
        if self.is_experimental:
            return self._do_update(new_code, source)

        # ═══════════════════════════════════════════════════════════════════
        # Rule 5: Stable skill + LLM → deferred validation
        # ═══════════════════════════════════════════════════════════════════
        self._pending_code = new_code
        self._pending_source = source
        return UpdateResult(
            success=False,
            reason="stable_needs_verification",
            need_verification=True,
            message="Stable skill requires execution verification before adopting new code."
        )

    def get_execution_code(self) -> str:
        """
        Return the code to use for execution.

        Returns pending code (if any), else the current code.
        This allows the new code to be used during execution validation without affecting node.code.

        Returns:
            str: code to use for execution
        """
        return getattr(self, '_pending_code', self.code)

    def has_pending_code(self) -> bool:
        """Check whether there is pending code."""
        return hasattr(self, '_pending_code')

    def confirm_pending(self, success: bool) -> ConfirmResult:
        """
        Confirm pending code after execution.

        Decides whether to adopt pending code based on execution result:
        - succeeded and not rejected → adopt the new code
        - failed or rejected → discard pending code; keep the original

        Args:
            success: whether execution succeeded

        Returns:
            ConfirmResult: confirmation result
        """
        if not hasattr(self, '_pending_code'):
            return ConfirmResult(adopted=False, message="no_pending")

        # Rejected updates are not adopted (wrapper architecture violations)
        if getattr(self, '_pending_rejected', False):
            covered_by = getattr(self, 'covered_by', 'unknown')
            message = f"Architecture violation rejected. Modify {covered_by} instead."
            self._clear_pending()
            return ConfirmResult(adopted=False, message=message)

        if success:
            pending_code = self._pending_code
            pending_source = getattr(self, '_pending_source', CodeSource.LLM)
            self._clear_pending()
            self._do_update(pending_code, pending_source)
            return ConfirmResult(adopted=True, message="New code adopted after successful execution.")
        else:
            self._clear_pending()
            return ConfirmResult(adopted=False, message="Execution failed. Original code preserved.")

    def _clear_pending(self) -> None:
        """Clear the pending state."""
        for attr in ['_pending_code', '_pending_source', '_pending_rejected']:
            if hasattr(self, attr):
                delattr(self, attr)

    def _do_update(self, code: str, source: CodeSource) -> UpdateResult:
        """
        Apply the actual update.

        Directly updates node.code and records the update source.

        Args:
            code: new code
            source: code source

        Returns:
            UpdateResult: update-success result
        """
        self.code = code
        self._last_update_source = source
        return UpdateResult(success=True, reason="updated")

    def _should_protect_wrapper(self, new_code: str) -> bool:
        """
        Decide whether wrapper architecture should be protected.

        Protection is triggered only when the following conditions hold:
        1. The node is marked is_covered (set by refactor)
        2. The new code no longer calls the function indicated by covered_by

        Meaning:
        - If the new code still calls covered_by → allow update (possibly a wrapper fix)
        - If the new code no longer calls covered_by → block (possibly a full re-implementation overriding the wrapper)

        Args:
            new_code: new code

        Returns:
            bool: whether the wrapper should be protected
        """
        if not getattr(self, 'is_covered', False):
            return False

        covered_by = getattr(self, 'covered_by', None)
        if not covered_by:
            return False

        # Check whether the new code still calls covered_by
        # Match function-call pattern via regex: functionName(
        call_pattern = rf'\b{re.escape(covered_by)}\s*\('

        # Still calls → no protection (allow wrapper fixes)
        # No longer calls → protect (block architecture-breaking change)
        return not bool(re.search(call_pattern, new_code))

    @classmethod
    def _migrate_parameters(cls, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """
        Migrate old parameter metadata to ensure compatibility with v5.1+ format.

        Migrations performed:
        1. Array parameters: Add supported_values if missing
        2. Semantic format: Convert old string format to new dict format

        Args:
            parameters: Parameter metadata dictionary

        Returns:
            Migrated parameter metadata
        """
        if not parameters:
            return parameters

        for param_name, param_info in parameters.items():
            if isinstance(param_info, dict):
                param_type = param_info.get("type")
                default = param_info.get("default")

                # Migration 1: Array parameters need supported_values
                if param_type == "array" and isinstance(default, list) and default:
                    if "supported_values" not in param_info:
                        param_info["supported_values"] = default

                # Migration 2: Convert old string semantic to new dict format
                semantic = param_info.get("semantic")
                if isinstance(semantic, str):
                    # Old format: "target_total" | "delta" | "config"
                    # New format: {"quantity_semantic": "...", "direction": "...", ...}
                    old_to_quantity = {
                        "target_total": "target_total",
                        "delta": "delta",
                        "config": "none",
                    }
                    quantity_semantic = old_to_quantity.get(semantic, "none")

                    # Infer direction from param name
                    param_lower = param_name.lower()
                    if "type" in param_lower and semantic != "config":
                        direction = "bidirectional"  # Need context to determine
                    else:
                        direction = "config"

                    param_info["semantic"] = {
                        "quantity_semantic": quantity_semantic,
                        "direction": direction,
                        "inferred_by": "legacy_migration",
                        "confidence": 0.5,
                    }

        return parameters

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SkillNode":
        """Construct a SkillNode from a dict (for deserialization)."""
        # Construct the node without code/description to avoid auto-creating an initial version
        node = cls.__new__(cls)  # do not call __init__
        node.name = data["name"]
        node.code = data.get("code", "")
        node.description = data.get("description", "")

        # Initialize other attributes
        node.preconditions = []
        node.expected_effects = []
        node.actual_effects = []
        node.versions = []
        node.statistics = SkillStatistics()
        node.gradients = SkillGradients()
        node.parents = []
        node.children = []
        node.in_degree = 0
        node.out_degree = 0
        node.stop_gradient = False
        node.is_task_specific = data.get("is_task_specific", False)  # restore task-specific marker from checkpoint

        # Debug log: record state during checkpoint restoration
        preconditions_data = data.get("preconditions", [])
        expected_effects_data = data.get("expected_effects", [])
        print(f"\033[35m[DEBUG] Restoring node '{node.name}' from checkpoint:\033[0m")
        print(f"\033[35m[DEBUG]   - preconditions in data: {len(preconditions_data)}\033[0m")
        print(f"\033[35m[DEBUG]   - expected_effects in data: {len(expected_effects_data)}\033[0m")

        # Restore preconditions
        for p_data in preconditions_data:
            node.preconditions.append(SkillPrecondition(
                description=p_data.get("description", ""),
                code=p_data.get("code", ""),
                state_representation=p_data.get("state_representation", {}),
                condition=p_data.get("condition"),
                source_skill=p_data.get("source_skill")
            ))

        # Restore expected effects
        for s_data in expected_effects_data:
            node.expected_effects.append(SkillEffect(
                description=s_data.get("description", ""),
                code=s_data.get("code", ""),
                state_representation=s_data.get("state_representation", {}),
                is_primary=s_data.get("is_primary", False),
                condition=s_data.get("condition"),
                source_skill=s_data.get("source_skill")
            ))

        # Debug log: record post-restoration state
        print(f"\033[35m[DEBUG] After restoration, node '{node.name}' state:\033[0m")
        print(f"\033[35m[DEBUG]   - preconditions restored: {len(node.preconditions)}\033[0m")
        print(f"\033[35m[DEBUG]   - expected_effects restored: {len(node.expected_effects)}\033[0m")

        # Restore actual effects
        for a_data in data.get("actual_effects", []):
            node.actual_effects.append(ActualEffect(
                execution_id=a_data.get("execution_id", ""),
                timestamp=a_data.get("timestamp", ""),
                description=a_data.get("description", ""),
                inventory_changes=a_data.get("inventory_changes", {}),
                position_changes=a_data.get("position_changes", {}),
                equipment_changes=a_data.get("equipment_changes", {}),
                block_changes=a_data.get("block_changes", []),
                verified=a_data.get("verified", False),
            ))

        # Restore version history
        for v_data in data.get("versions", []):
            # Restore preconditions
            preconditions = []
            for p_data in v_data.get("preconditions", []):
                preconditions.append(SkillPrecondition(
                    description=p_data.get("description", ""),
                    code=p_data.get("code", ""),
                    state_representation=p_data.get("state_representation", {}),
                    condition=p_data.get("condition"),
                    source_skill=p_data.get("source_skill")
                ))

            # Restore effects
            effects = []
            for e_data in v_data.get("effects", []):
                effects.append(SkillEffect(
                    description=e_data.get("description", ""),
                    code=e_data.get("code", ""),
                    state_representation=e_data.get("state_representation", {}),
                    is_primary=e_data.get("is_primary", False),
                    condition=e_data.get("condition"),
                    source_skill=e_data.get("source_skill")
                ))

            node.versions.append(SkillVersion(
                version=v_data.get("version", "1.0.0"),
                created_at=v_data.get("created_at"),
                change_log=v_data.get("change_log", ""),
                code=v_data.get("code", ""),
                description=v_data.get("description", ""),
                preconditions=preconditions,
                effects=effects,
                parameters=v_data.get("parameters", {}),
                value_function=v_data.get("value_function", 0.0),
                statistics_snapshot=v_data.get("statistics_snapshot", {}),
                update_source=v_data.get("update_source", "unknown"),
                update_reason=v_data.get("update_reason", ""),
                optimization_id=v_data.get("optimization_id"),
                used_feedbacks=v_data.get("used_feedbacks", []),
                backpropagation_info=v_data.get("backpropagation_info"),
                affected_subgraph=v_data.get("affected_subgraph", {}),
                sliding_window_size=v_data.get("sliding_window_size", 20),
                execution_window=v_data.get("execution_window", []),
            ))

        # Restore statistics
        stats_data = data.get("statistics", {})
        node.statistics.total_executions = stats_data.get("total_executions", 0)
        node.statistics.successful_executions = stats_data.get("successful_executions", 0)
        node.statistics.failed_executions = stats_data.get("failed_executions", 0)

        # Restore execution traces
        execution_traces_data = stats_data.get("execution_traces", [])
        for trace_data in execution_traces_data:
            # Restore actual_effects (List[ActualEffect])
            actual_effects_data = trace_data.get("actual_effects", [])
            actual_effects = []
            for ae_data in actual_effects_data:
                if isinstance(ae_data, dict):
                    actual_effects.append(ActualEffect(
                        execution_id=ae_data.get("execution_id"),
                        timestamp=ae_data.get("timestamp"),
                        description=ae_data.get("description", ""),
                        state_changes=ae_data.get("state_changes"),
                        inventory_changes=ae_data.get("inventory_changes"),
                        position_changes=ae_data.get("position_changes"),
                        equipment_changes=ae_data.get("equipment_changes"),
                        block_changes=ae_data.get("block_changes"),
                        pre_state=ae_data.get("pre_state"),
                        post_state=ae_data.get("post_state"),
                        verified=ae_data.get("verified", False),
                    ))

            trace = SkillExecutionTrace(
                execution_id=trace_data.get("execution_id"),
                timestamp=trace_data.get("timestamp"),
                trajectory_segment_id=trace_data.get("trajectory_segment_id"),
                trajectory_file=trace_data.get("trajectory_file"),
                task=trace_data.get("task"),
                context=trace_data.get("context"),
                environment_events=trace_data.get("environment_events", trace_data.get("mineflayer_events")),
                environment_state=trace_data.get("environment_state", trace_data.get("mineflayer_state")),
                pre_state=trace_data.get("pre_state"),  # Phase 1/2/3: pre-execution state
                post_state=trace_data.get("post_state"),  # Phase 1/2/3: post-execution state
                action_info=trace_data.get("action_info"),
                success=trace_data.get("success", False),
                error_message=trace_data.get("error_message"),
                error_stack=trace_data.get("error_stack"),  # backward compatible: older data may lack this field
                critique=trace_data.get("critique"),
                actual_effects=actual_effects if actual_effects else None,  # restore actual effects
                call_args=trace_data.get("call_args"),  # Phase 1: call arguments
                call_stack=trace_data.get("call_stack"),  # Phase 3: call stack
                call_depth=trace_data.get("call_depth", 1),  # Phase 3: call depth
                execution_status=trace_data.get("execution_status"),  # execution status
            )
            node.statistics.execution_traces.append(trace)

        # Restore graph structural info
        graph_info = data.get("graph_info", {})
        node.parents = graph_info.get("parents", [])
        node.children = graph_info.get("children", [])
        node.in_degree = graph_info.get("in_degree", 0)
        node.out_degree = graph_info.get("out_degree", 0)

        # Restore optimization control
        node.stop_gradient = data.get("stop_gradient", False)

        # Restore gradient info
        gradients_data = data.get("gradients", {})

        # Handle legacy format (list of strings) and new format (list of SkillGradientItem)
        def parse_gradient_items(items_data):
            result = []
            for item_data in items_data:
                if isinstance(item_data, str):
                    # Legacy format: plain strings
                    result.append(SkillGradientItem(content=item_data))
                elif isinstance(item_data, dict):
                    # New format: dicts
                    result.append(SkillGradientItem(
                        content=item_data.get("content", ""),
                        used_in_optimization=item_data.get("used_in_optimization", False),
                        optimization_id=item_data.get("optimization_id"),
                        timestamp=item_data.get("timestamp", datetime.now().isoformat())
                    ))
            return result

        node.gradients.reflections = parse_gradient_items(gradients_data.get("reflections", []))
        node.gradients.feedback = parse_gradient_items(gradients_data.get("feedback", []))
        node.gradients.optimization_suggestions = parse_gradient_items(
            gradients_data.get("optimization_suggestions", [])
        )

        # Restore parameter metadata
        node.parameters = data.get("parameters", {})

        # Migration: ensure all array parameters have supported_values (backward compatibility with legacy metadata)
        node.parameters = cls._migrate_parameters(node.parameters)

        # Restore refactor/coverage info
        refactor_info = data.get("refactor_info", {})
        node.is_covered = refactor_info.get("is_covered", False)
        node.covered_by = refactor_info.get("covered_by", None)
        node.is_general_skill = refactor_info.get("is_general_skill", False)

        # Restore coverage_type (supports conversion from legacy data format)
        from .coverage import CoverageType
        coverage_type_str = refactor_info.get("coverage_type")
        # Backward compatible: support reading from the legacy refactor_type field
        legacy_refactor_type = refactor_info.get("refactor_type")
        if coverage_type_str:
            node.coverage_type = CoverageType.from_refactor_type(coverage_type_str)
        elif legacy_refactor_type:
            # Convert from the legacy data format
            node.coverage_type = CoverageType.from_refactor_type(legacy_refactor_type)
        else:
            node.coverage_type = None

        # Restore deprecation info
        deprecation_info = data.get("deprecation_info", {})
        node.is_deprecated = deprecation_info.get("is_deprecated", False)
        node.deprecation_reason = deprecation_info.get("deprecation_reason", None)
        node.deprecated_for_task = deprecation_info.get("deprecated_for_task", None)
        # Restore gradual-deprecation fields
        node.consecutive_failures = deprecation_info.get("consecutive_failures", 0)
        node.task_failures = deprecation_info.get("task_failures", {})
        node.deprecation_threshold = deprecation_info.get("deprecation_threshold", 3)
        node.task_failure_threshold = deprecation_info.get("task_failure_threshold", 2)

        # Restore experimental-related fields
        node.is_experimental = deprecation_info.get("is_experimental", False)
        node.first_failure_reason = deprecation_info.get("first_failure_reason", None)
        node.experimental_retry_count = deprecation_info.get("experimental_retry_count", 0)
        node.max_experimental_retries = deprecation_info.get("max_experimental_retries", 4)
        node.experimental_task = deprecation_info.get("experimental_task", None)

        # Restore Experimental Skill lifecycle-management fields (newly added)
        node.created_for_task = deprecation_info.get("created_for_task", None)
        node.is_verified = deprecation_info.get("is_verified", False)

        # Restore semantic confidence
        node.semantics_confidence = data.get("semantics_confidence", 0.0)

        # Restore value-function parameters
        value_function_params = data.get("value_function_params", {})
        node.value_function_lambda = value_function_params.get("lambda", 1.0)
        node.value_function_alpha = value_function_params.get("alpha", 1.0)
        node.value_function_beta = value_function_params.get("beta", 1.0)

        return node
