#!/bin/bash
# Headless Fabric server one-time setup for PSN.
#
# Downloads the Fabric installer, builds a self-contained Fabric server
# (Minecraft + Fabric loader + bundled libraries) under
# installation/fabric_server/, accepts the EULA on behalf of the user, and
# materializes a `server.properties` derived from
# installation/fabric_server_config.json. Idempotent: re-running upgrades
# the server jar but preserves the world directory.
#
# Triggered automatically by ./skillnet.sh --mc-mode=headless on first run.
# Can also be invoked manually:
#     bash installation/setup_fabric_server.sh

set -euo pipefail

PSN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERVER_DIR="$PSN_ROOT/installation/fabric_server"
CONFIG_FILE="$PSN_ROOT/installation/fabric_server_config.json"

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "ERROR: $CONFIG_FILE not found." >&2
    exit 1
fi

# Read config via python (always available in PSN env)
read_cfg() {
    python3 -c "import json,sys; print(json.load(open('$CONFIG_FILE')).get('$1', ''))"
}

MC_VER=$(read_cfg minecraft_version)
LOADER_VER=$(read_cfg fabric_loader_version)
INSTALLER_VER=$(read_cfg fabric_installer_version)

if [[ -z "$MC_VER" || -z "$LOADER_VER" || -z "$INSTALLER_VER" ]]; then
    echo "ERROR: minecraft_version / fabric_loader_version / fabric_installer_version must be set in $CONFIG_FILE" >&2
    exit 1
fi

echo "[setup_fabric_server] target: Minecraft $MC_VER + Fabric loader $LOADER_VER (installer $INSTALLER_VER)"

# Pre-flight: java
if ! command -v java >/dev/null 2>&1; then
    echo "ERROR: java is required but not found in PATH." >&2
    echo "Install OpenJDK 17 (or newer for MC 1.20+) and re-run." >&2
    exit 1
fi
JAVA_VER=$(java -version 2>&1 | head -1)
echo "[setup_fabric_server] using $JAVA_VER"

mkdir -p "$SERVER_DIR"
cd "$SERVER_DIR"

# Fabric publishes a pre-bundled "server launcher" jar that contains the
# installer + loader and downloads the matching Minecraft server jar on
# first run. One file, no -downloadMinecraft step.
# URL form: /v2/versions/loader/{mc}/{loader}/{installer}/server/jar
LAUNCHER_JAR="fabric-server-launcher.jar"
LAUNCHER_URL="https://meta.fabricmc.net/v2/versions/loader/${MC_VER}/${LOADER_VER}/${INSTALLER_VER}/server/jar"

# Always re-download to support upgrading; small jar (~250 KB).
echo "[setup_fabric_server] downloading $LAUNCHER_JAR ..."
echo "                      from $LAUNCHER_URL"
curl -fL -o "$LAUNCHER_JAR" "$LAUNCHER_URL"

# Accept EULA before any server run so the next java -jar invocation
# (whether from this script or run_fabric_server.sh) can proceed.
echo "eula=true" > eula.txt

# Render server.properties from the JSON config BEFORE the bootstrap run.
# The launcher reads it at startup; without it the server tries to bind
# to its hard-coded default port (25565) which may conflict with the
# user's existing setup.
python3 - "$CONFIG_FILE" "$SERVER_DIR/server.properties" <<'PY'
import json, sys
cfg = json.load(open(sys.argv[1]))
# Map our config keys to canonical server.properties keys.
props = {
    "server-port":              cfg["server_port"],
    "server-ip":                cfg["server_ip"],
    "online-mode":              str(cfg["online_mode"]).lower(),
    "max-players":              cfg["max_players"],
    "view-distance":            cfg["view_distance"],
    "simulation-distance":      cfg["simulation_distance"],
    "level-name":               cfg["level_name"],
    "level-seed":               cfg["level_seed"],
    "level-type":               cfg["level_type"],
    "generate-structures":      str(cfg["generate_structures"]).lower(),
    "gamemode":                 cfg["gamemode"],
    "difficulty":               cfg["difficulty"],
    "force-gamemode":           str(cfg["force_gamemode"]).lower(),
    "hardcore":                 str(cfg["hardcore"]).lower(),
    "pvp":                      str(cfg["pvp"]).lower(),
    "allow-flight":             str(cfg["allow_flight"]).lower(),
    "spawn-monsters":           str(cfg["spawn_monsters"]).lower(),
    "spawn-animals":            str(cfg["spawn_animals"]).lower(),
    "spawn-npcs":               str(cfg["spawn_npcs"]).lower(),
    # allow-cheats is enforced via OP'ing the bot user at runtime; the
    # server.properties has no allow-cheats key. The bot is opped to
    # gain /give /tp etc. when this is true.
}
with open(sys.argv[2], "w") as f:
    f.write("# Generated by installation/setup_fabric_server.sh — do not edit by hand.\n")
    f.write("# Edit installation/fabric_server_config.json and re-run setup instead.\n")
    for k, v in props.items():
        f.write(f"{k}={v}\n")
print(f"wrote {sys.argv[2]}")
PY

# Persist allow_cheats decision for run script to consume on launch.
python3 -c "
import json
cfg = json.load(open('$CONFIG_FILE'))
with open('$SERVER_DIR/.psn_allow_cheats', 'w') as f:
    f.write(str(cfg['allow_cheats']).lower())
"

# Trigger first-run bootstrap so the launcher downloads server.jar +
# Minecraft libraries + generates the world dir. server.properties is
# already on disk so this run binds to the correct port. We stop the
# server once spawn finishes — net effect: a populated
# installation/fabric_server/ dir with all binaries downloaded and a
# pre-generated world, ready for run_fabric_server.sh.
echo "[setup_fabric_server] bootstrapping (downloads server.jar on first run) ..."
BOOTSTRAP_LOG="$SERVER_DIR/.bootstrap.log"
java -Xms512M -Xmx1024M -jar "$LAUNCHER_JAR" nogui > "$BOOTSTRAP_LOG" 2>&1 &
BOOTSTRAP_PID=$!
for _ in $(seq 1 180); do
    if grep -q 'Done (' "$BOOTSTRAP_LOG" 2>/dev/null; then
        break
    fi
    if ! ps -p "$BOOTSTRAP_PID" >/dev/null 2>&1; then
        echo "ERROR: bootstrap server exited unexpectedly. Tail of log:" >&2
        tail -30 "$BOOTSTRAP_LOG" >&2
        exit 1
    fi
    sleep 1
done

if grep -q 'Done (' "$BOOTSTRAP_LOG" 2>/dev/null; then
    echo "[setup_fabric_server] bootstrap successful; shutting down ..."
    kill -TERM "$BOOTSTRAP_PID" 2>/dev/null || true
    for _ in $(seq 1 30); do
        ps -p "$BOOTSTRAP_PID" >/dev/null 2>&1 || break
        sleep 1
    done
    ps -p "$BOOTSTRAP_PID" >/dev/null 2>&1 && kill -KILL "$BOOTSTRAP_PID" 2>/dev/null || true
else
    echo "ERROR: bootstrap did not reach 'Done' within 180s. Tail of log:" >&2
    tail -30 "$BOOTSTRAP_LOG" >&2
    kill -KILL "$BOOTSTRAP_PID" 2>/dev/null || true
    exit 1
fi

echo ""
echo "[setup_fabric_server] done."
echo "  server dir:    $SERVER_DIR"
echo "  launcher jar:  $SERVER_DIR/fabric-server-launcher.jar"
echo "  port:          $(read_cfg server_port)"
echo "  start it with: bash installation/run_fabric_server.sh"
